### ISSUE TITLE
Return results to host?

### ISSUE THREAD

**Issue by polarathene** [arrayfire/arrayfire-rust#134]
It seems I should use the `host` method on an `Array` mentioned in the docs [here](http://arrayfire.org/arrayfire-rust/arrayfire/struct.Array.html#method.host). The [repo md docs](https://github.com/arrayfire/arrayfire-rust/blob/devel/doc/getting_started.md) has a 404 link when referencing [Array::host()](https://github.com/arrayfire/arrayfire-rust/blob/devel/doc/struct.Array.html#method.host) and lacks an example(I didn't see any in the other docs or the repo examples).

If I did some random integer math with example dim (5,2,1,1), how would you return to the host results that were even numbers? Or all results within a range, etc. The variable given to the host function parameter seems to require an array of a fixed size at compile time? I'd assume the size is equal to the number of elements? I'm still not too familiar with Rust but it doesn't seem to let me define the length dynamically by calling `.elements()` on the Array.

**Comment by ultimaRatio** [comment]
Hi,

a very short example (i hope it'll help you) where d is an af::Array of u8 values 
let mut truc = vec![0u8;d.elements() as usize];
d.host(&mut truc);

i don't know about indexing (still fighting with it)

**Comment by polarathene** [comment]
@ultimaRatio Thanks, I've managed to figure this out and will share an example here for docs if I find time. I ran into a problem for a while where I expected u32 value that I had been working with but the array returned from AF eq() was actually u8 and didn't throw any errors giving me a result that didn't make sense at first.

I can help you with indexing probably if the advice I gave on your issue is not enough, reply to me there what you have to work with and what you expect to get as a result of the indexing.

**Comment by 9prady9** [comment]
The documentation `repo md docs` link you shared earlier is not from current release of arrayfire-rust crate.  
 The markdown file you are looking at is from the devel branch on github repository landing page. The current release's documentation is available [here](http://arrayfire.github.io/arrayfire-rust/arrayfire/index.html) and it is hyper-linked on the repo landing page in the [documentation section](https://github.com/arrayfire/arrayfire-rust#documentation).

`eq()` is a comparison operation and thus the result of that operation is boolean in nature irrespective of the input Array type. This is expected behaviour of this function. ArrayFire's upstream implementation represents boolean results using `char` C type. So, the output of eq() call should be an Array of type `DType::B8` - the equivalent enum value of ArrayFire C API is `b8`.

We are sorry for any inconvenience caused due to lack of mention in the documentation. Improving documentation is an on-going effort and we are constantly working on it as per our bandwidth. We appreciate and love contributions from the community. Please feel free to send in a PR with an example show casing how to use `Array::host()`.
