### ISSUE TITLE
Host array of eq is incorrect

### ISSUE THREAD

**Issue by polarathene** [arrayfire/arrayfire-rust#136]
When doing an `eq` or `neq` on two Arrays, `print()` will give the expected result such as `[0, 1, 0]`, when moved to the host I would see `[256, 0, 0]`. For `neq` `[1, 0, 1]` would convert to `[65537, 0, 0]`.

```Rust
let length = result.elements() as usize;
let mut rdata: Vec<u32> = vec![0; length];
result.host::<u32>(&mut rdata);
```

I've found out changing `u32` to `u8` gives the correct array values. The [docs](http://arrayfire.org/arrayfire-rust/arrayfire/fn.eq.html) don't mention the Array returned is `u8`. I'm not familiar enough with Rust but would assume if the output for eq/neq is always in `u8` values that could be typed and the compiler would pick up on it for the developer to understand what happened?

**Comment by 9prady9** [comment]
`eq()` is a comparison operation and thus the result of that operation is boolean in nature irrespective of the input Array type. This is expected behaviour of this function. ArrayFire's upstream implementation represents boolean results using `char` C type. So, the output of eq() call should be an Array of type `DType::B8` - the equivalent enum value of ArrayFire C API is `b8`. Hence, one would only get correct values if a Vector of u8 or s8 is used to retrieve the values to host side.

I shall leave this issue open until the docs are updated indicating the output Array's type for such comparison operations. Thank you.

I understand that you have requested for type-checked Arrays, here and in other issues you have created, however changing the current wrapper to implement type check is much bigger change. We have left the [issue#98](https://github.com/arrayfire/arrayfire-rust/issues/98) open for discussions related to type checked Arrays.
