### ISSUE TITLE
Fix reorder documentation for second argument

### ISSUE THREAD

**Issue by srenevey** [arrayfire/arrayfire-rust#202]
Using reorder() with what seems to be valid inputs makes the thread panic. 

MWE:
```rust
let val = [1., 2., 3., 4., 5., 6., 7., 8., 9., 10., 11., 12.];
let arr = Array::new(&val, Dim4::new(&[2, 3, 1, 2]));
let re_arr = reorder(&arr, Dim4::new(&[3, 2, 1, 2]));
```

Results in:

```
thread 'main' panicked at 'Error message: Size is incorrect
Last error: In function af_err af_reorder(af_array *, const af_array, const af::dim4 &)
In file src/api/c/reorder.cpp:84
Invalid dimension for argument 5
Expected: rdims[i] == allDims[rdims[i]]...
```

**Comment by 9prady9** [comment]
@srenevey the target output dimensions (axes) should be 0-based index i.e. they are values from 0 to 3

Your example is basically transpose and thus dim4 you pass to reorder should be dim4(1, 0, 2, 3) because you want to swap data along dimension 0 and 1. It is not an failure, rather a proper check done. Notice how the error message is checking `rdims[i] == allDims[rdims[i]]` I understand it is not understandable, sorry about it. We will improve that error message.

**Comment by srenevey** [comment]
It wasn't clear that the second argument was how the axes should be reordered. I thought it was the number of elements per dimension. Thanks for the clarification.

**Comment by 9prady9** [comment]
I shall keep this issue open until I make it clear in the documentation. Thanks once again for reporting it!.
