### ISSUE TITLE
Controversial seq! macro usage examples

### ISSUE THREAD

**Issue by videobitva** [arrayfire/arrayfire-rust#301]
Hello!

The seq! macro usage example, which could be found [here](https://arrayfire.org/arrayfire-rust/book/indexing.html), is pretty much controversial and made me frustrating for several hours while trying to figure out what is wrong with me and my coding skills.

Take a look at this section:

```rust
let b = constant(1.0 as f32, dim4!(3, 3));
let seqs = [seq!(1:3:1), seq!()];
assign_seq(&mut a, &seqs, &b);
```

Here we can clearly see the way to use this macro: 
```rust
seq!(start:stop:step);
```

However, this does not work, because the way it supposed is to be (according to reality and [this doc page](https://arrayfire.org/arrayfire-rust/arrayfire/macro.view.html)) is to be like this: 
```rust
seq!(start,stop,step);
```

As this issue name has *controversial* in it, time to take a look at this bit of docs:
```rust
let seqs = &[Seq::new(1u32, 3, 1), Seq::default()];
let _sub = index(&a, seqs);
//af_print!("a(seq(1,3,1), span)", sub);
// [3 5 1 1]
//     0.6720     0.3932     0.0621     0.9159     0.8434
//     0.5339     0.2706     0.7089     0.0231     0.1328
//     0.1386     0.9455     0.9434     0.2330     0.2657
```
Here the correct way of code usage was given, but the problem is that it was commented out, thus while looking through you can easily miss it. If we continue reading, we can easily see (as we *already* discovered it), that **every** single example of the correct way of usage of this macro was commented out, while the wrong way was kept.

Of course, all of this would not be a problem if I firstly looked through the docs [here](https://arrayfire.org/arrayfire-rust/arrayfire/index.html), but, the thing is, in the first section it clearly states that you should use the tutorials, which have misleading info in it. Please correct the tutorial so there will be less people in pain.

**Comment by 9prady9** [comment]
@videobitva Sorry about the delay in my response.

There are variations in syntax due to the limitation on how `:` could be interpreted in a macro when `expr` type is used. So, I couldn't use `:` colon as delimiter for all cases. `:` delimiter can only be used with literals. When expressions are passed in as the sequence macro arguments, I use `,` as delimiter.

I think to avoid confusion, perhaps I should switch to `,` as delimiter in all cases. Another thing would be to add some examples to tutorial with expression based arguments rather than constant literals.

Hence, this is not a bug but rather just difference in syntax of `seq` macros when arguments are expressions vs constant literals.

**Comment by 9prady9** [comment]
Hope the clarification cleared the confusion. I have also opened a new issue to fix the consistency problem in seq macro. Please follow it's updates over there. 

https://github.com/arrayfire/arrayfire-rust/issues/306
