### ISSUE TITLE
[Build] RUSTSEC-2020-0071: Potential segfault in the time crate

### ISSUE THREAD

**Issue by c0dearm** [arrayfire/arrayfire-rust#325]
# Description
`arrayfire-rust` depends on the `mnist` package that in turn depends on the `time` crate.

The following security advisory was raised tonight regarding the `time` crate: https://github.com/c0dearm/mushin/issues/16

I think there are a few things to do here:
* Upgrade the `mnist` package so that the security vulnerability is not there anymore.
* Set up a GitHub workflow to check for package vulnerabilities (like it is done in the `mushin` project)
* Is `mnist` really a required dependency? Would it be possible to have it only as a dev dependency or in a Cargo feature flag?

**Comment by 9prady9** [comment]
@c0dearm Firstly, thank you for bringing this to my attention.

I should have caught this earlier, this should be in dev-dependencies of cargo manifest indeed. Must have slipped through. Sorry about that. However, rest assured that crate from crates.io won't have it as dependency and thus users of arrayfire crate are safe. I have addressed it here already https://github.com/arrayfire/arrayfire-rust/pull/326

A git hub action to check for vulnerabilities would be definitely useful in general. I think it should run on a PR only if Cargo file is changed. Otherwise, running it on master branch for push event would suffice.

**Comment by c0dearm** [comment]
Hi! It can be just scheduled to run once a day or so.

Even if there's no update in the `Cargo.lock` a new vulnerability might be discovered in one of the package versions.

**Comment by 9prady9** [comment]
@c0dearm would you be interested in submitting a PR for this job ? I have created an issue for this https://github.com/arrayfire/arrayfire-rust/issues/327

**Comment by c0dearm** [comment]
Sure! I will try to find some time between today and tomorrow 🙂

**Comment by 9prady9** [comment]
> Sure! I will try to find some time between today and tomorrow slightly_smiling_face

thank you
