### ISSUE TITLE
Graphics aliasing when plotting GPU Array

### ISSUE THREAD

**Issue by jramapuram** [arrayfire/arrayfire-rust#56]
I see this behavior consistently when using linux or OSX. It works fine if it is a CPU backed array.
![aliasing](http://i.imgur.com/QzhD2Wk.png)

**Comment by 9prady9** [comment]
@jramapuram which aliasing are you referring to here ? That white triangle looks odd in that plot! Can you please post the CPU rendering for reference.

**Comment by jramapuram** [comment]
Yea, the white triangle was the aliasing I mentioned. Aliasing was just a broad term to depict this.
The issue happens on CUDA or OpenCL backends btw. [Here](https://github.com/jramapuram/hal/blob/hotfix/swapping/src/plot.rs) is the simple code to do the plotting.
Here is the same thing rendered on CPU:
![img](http://i.imgur.com/apoNP7e.png)

**Comment by 9prady9** [comment]
The axes labels and titles are missing in the GPU version which is quite frankly odd because rendering code is identical for any backend, only the process of data update changes for each backend. Even if we assume backend is some how effecting the rendering, it can only effect the plot itself not the chart related details. Were you able to reproduce this in the native library ( i mean in a C/C++ program) ?

**Comment by jramapuram** [comment]
Yea I thought the axis not being present was rather strange. 
Haven't had the time to work through a C/Cpp program yet. 
Will try to get to it if I have some time.

**Comment by jramapuram** [comment]
Resolved with 3.3.0
