### ISSUE TITLE
Problems with `dot` function

### ISSUE THREAD

**Issue by cathalgarvey** [arrayfire/arrayfire-rust#99]
I'll break this issue out of the #98 discussion..

I've reduced the problem-code down to the below. It looks like the `dot` function crashes on multidimensional data?

# Works

```rust
#[macro_use(af_print)]
extern crate arrayfire as af;
use af::{print_gen};

fn main() {
    let x = af::Array::new(&[0f32, 0f32, 1f32, 0f32], af::Dim4::new(&[4, 1, 1, 1]));
    let y = af::Array::new(&[0f32, 0f32, 1f32, 1f32], af::Dim4::new(&[4, 1, 1, 1]));
    let l1_dots = af::dot(&x, &y, af::MatProp::NONE, af::MatProp::NONE);
    af_print!("l1_dots", l1_dots);
}
```

# Runtime Crash

```rust
#[macro_use(af_print)]
extern crate arrayfire as af;
use af::{print_gen};

fn main() {
    let x = af::Array::new(&[0f32, 0f32, 1f32, 0f32], af::Dim4::new(&[2, 2, 1, 1]));
    let y = af::Array::new(&[0f32, 0f32, 1f32, 1f32], af::Dim4::new(&[2, 2, 1, 1]));
    let l1_dots = af::dot(&x, &y, af::MatProp::NONE, af::MatProp::NONE);
    af_print!("l1_dots", l1_dots);
}
```

**Comment by pavanky** [comment]
@cathalgarvey What is a runtime crash ? Is it showing anything ? Because right now 2D arrays are not supported with dot. You should look at `matmul` which performs matrix multiplication and is what you need.

**Comment by pavanky** [comment]
@cathalgarvey Since there is no reasonable way to handle errors in rust (other than forcing the users to check for errors at each function call), the decision was made to panic when you send in the wrong arguments. Recent versions of rust have enabled functionality to recover from panics: https://doc.rust-lang.org/std/panic/fn.catch_unwind.html

If you look at the error messages being printed before the panic, they should be pretty indicative of what is happening. If you are not seeing those messages let us know so it can be fixed.

**Comment by AtheMathmo** [comment]
I'm also running into some issues with the dot function, down to size issues. This line from the documentation in particular has me confused:

> This function returns the scalar product of two equal sized vectors or **between a matrix and a vector**.

(Emphasis mine)

In this latter case what are the expected dimensions? I assumed that in this case `dot` performs a matrix multiplication with the vector, and `matmul` is reserved for two 2d arrays. But this seems not to be the case.
